name = "flakeforecast"
pages_build_output_dir = "."
compatibility_date = "2026-04-16"

[[d1_databases]]
binding = "DB"
database_name = "flake_forecasts"
database_id = "2c6a0a1b-2f7c-4668-ac6a-6f5156bb7dcf"

